[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  external_node_modules = ["@supabase/supabase-js", "bcrypt", "crypto"]
  node_bundler = "esbuild"
  
[functions.api]
  node_bundler = "esbuild"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Test redirect for debugging
[[redirects]]
  from = "/test/*"
  to = "/.netlify/functions/test/:splat"
  status = 200
